// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIHkycShLYJh0g_ImOS6ZaWwIRnipc7bU',
    appId: '1:1070540053005:web:ef67438e5a481825dcd344',
    messagingSenderId: '1070540053005',
    projectId: 'medication-reminder-app-75cd0',
    authDomain: 'medication-reminder-app-75cd0.firebaseapp.com',
    storageBucket: 'medication-reminder-app-75cd0.appspot.com',
    measurementId: 'G-ECXWYT263W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2KMgefZj-T9s92QgxP7S303Kvtj04N0Y',
    appId: '1:1070540053005:android:a01fe2528e96c91adcd344',
    messagingSenderId: '1070540053005',
    projectId: 'medication-reminder-app-75cd0',
    storageBucket: 'medication-reminder-app-75cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArv0F2KbUOHQssZtqhgN24HVQJaKgljGM',
    appId: '1:1070540053005:ios:eb5a3413f66a2011dcd344',
    messagingSenderId: '1070540053005',
    projectId: 'medication-reminder-app-75cd0',
    storageBucket: 'medication-reminder-app-75cd0.appspot.com',
    iosBundleId: 'com.example.medicationReminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArv0F2KbUOHQssZtqhgN24HVQJaKgljGM',
    appId: '1:1070540053005:ios:eb5a3413f66a2011dcd344',
    messagingSenderId: '1070540053005',
    projectId: 'medication-reminder-app-75cd0',
    storageBucket: 'medication-reminder-app-75cd0.appspot.com',
    iosBundleId: 'com.example.medicationReminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIHkycShLYJh0g_ImOS6ZaWwIRnipc7bU',
    appId: '1:1070540053005:web:88e7e931a028e112dcd344',
    messagingSenderId: '1070540053005',
    projectId: 'medication-reminder-app-75cd0',
    authDomain: 'medication-reminder-app-75cd0.firebaseapp.com',
    storageBucket: 'medication-reminder-app-75cd0.appspot.com',
    measurementId: 'G-70LFRKRSWY',
  );
}
